#!/bin/sh

[ -f ~/.xprofile ] && . ~/.xprofile

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/* ; do
    if [ -x "$f" ]; then
      . "$f"
    fi
  done
  unset f
fi

#exec ck-launch-session dbus-launch --auto-syntax --exit-with-session startxfce4

#if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
  #eval `dbus-launch --sh-syntax --exit-with-session`
  #export DBUS_SESSION_BUS_ADDRESS
  #export DBUS_SESSION_BUS_PID
#fi
#exec ck-launch-session dbus-launch --sh-syntax --exit-with-session startxfce4
exec startxfce4
