path=(
  $HOME/bin
  /usr/local/(s|)bin
  /(s|)bin
  /usr/(s|)bin
  $path
  )
#存在しないディレクトリを排除
path=($^path(N-/))

export ZDOTDIR=$(dirname $(readlink -f $HOME/.zshenv))
export DROPBOX=${ZDOTDIR/Dropbox*/Dropbox}

export skip_global_compinit=1

if type lv &>/dev/null; then
  export PAGER=lv
  export LV="-c -l -T8192"
else
  export PAGER=less
fi

if type vim &>/dev/null; then
  export EDITOR=vim
fi

if [ -f /etc/issue ]; then
  if grep -q "Arch Linux" /etc/issue ; then
    #[ -f /etc/profile ] && . /etc/profile
    # Arch Linux, system zprofile is /etc/profile
    export DISTRO="Arch"
  elif grep -q "Ubuntu" /etc/issue ; then
    export DISTRO="Ubuntu"
    export DEBIAN_BUILDARCH=pentium4
  fi
fi

