case ${OSTYPE} in
  linux*);
    export DROPBOX="$HOME/Dropbox"
    ;;
  cygwin*);
    export DROPBOX="/cygdrive/d/Dropbox"
    ;;
esac

export ZDOTDIR="$DROPBOX/src/dotfiles/zsh"
export skip_global_compinit=1
